@baseUrl = http://localhost:4004

### ------------------------------------------------------------------------

### ------------------------------------------------------------------------
# Create a new post
# @name createNewPost
POST {{baseUrl}}/movie/Posts
Content-Type: application/json

{
  "title": "Direct"
}

###

POST {{baseUrl}}/movie/Posts
Content-Type: application/json

{
  "title": "Actor"
}
### ------------------------------------------------------------------------

POST {{baseUrl}}/movie/Locations
Content-Type: application/json

{
  "country_code": "ru",
  "title": "Москва"
}
### ------------------------------------------------------------------------

POST {{baseUrl}}/movie/Locations
Content-Type: application/json

{
  "country_code": "us",
  "title": "Wasington"
}
### ------------------------------------------------------------------------

POST {{baseUrl}}/movie/Locations
Content-Type: application/json

{
  "country_code": "de",
  "title": "Berlin"
}

### ------------------------------------------------------------------------

POST {{baseUrl}}/movie/Movies
Content-Type: application/json

{
  "title": "Romeo and Juliet"
}

### ------------------------------------------------------------------------

POST {{baseUrl}}/movie/Movies
Content-Type: application/json

{
  "title": "Догони если сможешь"
}
### ------------------------------------------------------------------------

POST {{baseUrl}}/movie/Movies
Content-Type: application/json

{
  "title": "Побег из шоушенка"
}
###


POST {{baseUrl}}/movie/Movies
Content-Type: application/json

{
  "title": "The Matrix"
}

### ------------------------------------------------------------------------
# @name getPost
GET {{baseUrl}}/admin/Post?$filter=title eq 'Actor'

###

@postID = {{getPost.response.body.$.value[0].ID}}

POST {{baseUrl}}/movie/Employee
Content-Type: application/json

{
  "post_ID" : "{{postID}}",
  "firstName": "Sergey1",
  "lastName": "Burunov",
  "Emails": [
    { "kind": "work", "address": "s.bur@company.com" },
    { "kind": "personal", "address": "s.bur@gmail.com" }
  ]
}

### ------------------------------------------------------------------------
GET {{baseUrl}}/movie/Employee?$filter=post/title eq 'Actor'&$expand=post
Accept: application/json

### ------------------------------------------------------------------------

# @name getMovie
GET {{baseUrl}}/movie/Movies?$filter=title eq '2'

###

@movieID = {{getMovie.response.body.$.value[0].ID}}


# @name getEmployee
GET {{baseUrl}}/movie/Employee?$filter=firstName eq 'Sergey1' and lastName eq 'Burunov'

###
@employeeID = {{getEmployee.response.body.$.value[0].ID}}

POST {{baseUrl}}/movie/Movies(ID={{movieID}},IsActiveEntity=true)/staff
Content-Type: application/json

{
  "employee_ID": "{{employeeID}}"
}

###
GET {{baseUrl}}/movie/Movies?$filter=title eq 'The Matrix'&$expand=staff

###
GET {{baseUrl}}/movie/Employee?$filter=firstName eq 'Sergey' and lastName eq 'Burunov'&$expand=staff

###
GET {{baseUrl}}/movie/EmployNames
Accept: application/json