@baseUrl = http://localhost:4004

###

POST {{baseUrl}}/movie/Movies
Content-Type: application/json

{
  "title": "Romeo and Juliet"
}

### ------------------------------------------------------------------------
# @name getMovie
GET {{baseUrl}}/movie/Movies?$filter=title eq 'The Matrix'

###

@movieID = {{getMovie.response.body.$.value[0].ID}}

POST {{baseUrl}}/movie/pushMovieStatus
Accept-Language: ru
Content-Type: application/json

{
  "movieID": "{{movieID}}"
}