@baseUrl = http://localhost:4004

### ------------------------------------------------------------------------
# @name getMovie
GET {{baseUrl}}/movie/Movies?$filter=title eq 'The Matrix'

###

@movieID = {{getMovie.response.body.$.value[0].ID}}

GET {{baseUrl}}/movie/getActorsCount
Accept-Language: ru
Content-Type: application/json

{
  "movieID": "{{movieID}}"
}
###
GET {{baseUrl}}/movie/getMoviesByStatus
Accept-Language: ru
Content-Type: application/json

{
  "status": 0
}
###
GET {{baseUrl}}/movie/MVStatus(0)/Set 
Accept: application/json

###
GET {{baseUrl}}/movie/Movies
Accept: application/json