@baseUrl = http://localhost:4004

### ------------------------------------------------------------------------

### ------------------------------------------------------------------------
# Create a new post
# @name createNewPost
POST {{baseUrl}}/movie/Posts
Content-Type: application/json

{
  "title": "Direct"
}

### ------------------------------------------------------------------------

POST {{baseUrl}}/admin/Locations
Content-Type: application/json

{
  "country_code": "ru",
  "title": "Москва"
}

### ------------------------------------------------------------------------

POST {{baseUrl}}/admin/Locations
Content-Type: application/json

{
  "country_code": "de",
  "title": "Berlin"
}

### ------------------------------------------------------------------------

POST {{baseUrl}}/movie/Movies
Content-Type: application/json

{
  "title": "Romeo and Juliet"
}

